@echo off

SET PARTITION=%~d0
SET WORKING_DIR=%~dp0
SET DRV_LETTER=%CD:~0,1%
SET FULL_PATH=%CD:~3,-1%%CD:~-1%
SET DOS2UNIX=%WORKING_DIR%bin/dos2unix

SET BASHRC_SRC=%WORKING_DIR%.bashrc
SET BASHRC_NEW=%WORKING_DIR%home\michalliu\.bashrc

COPY %BASHRC_SRC% %BASHRC_NEW% > nul

ECHO # !ATTENTION! DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN EVERY TIME  >> %BASHRC_NEW%
ECHO drive=$(echo '%DRV_LETTER%' ^| tr [':upper:'] [':lower:']) >> %BASHRC_NEW%
ECHO path=$(echo '%FULL_PATH%' ^| tr '\\' '/') >> %BASHRC_NEW%
ECHO cd /cygdrive/$drive/"$path" >> %BASHRC_NEW%
ECHO alias awsoa="aws --curl=\"curl --insecure --proxy http://web-proxy.oa.com:8080\" -vvv" >> %BASHRC_NEW%
ECHO alias awssock="aws --curl=\"curl --insecure --socks localhost:11000\" -vvv" >> %BASHRC_NEW%

%DOS2UNIX% %BASHRC_NEW% > nul 2>&1

GOTO TTY

:BASH
%WORKING_DIR%bin\bash --login -i
GOTO EXIT

:TTY
start %WORKING_DIR%bin\mintty -
GOTO EXIT

:EXIT
